# Generated by Django 3.1.6 on 2021-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=1)),
                ('ids', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(default='Description')),
            ],
        ),
    ]
